In [64]:
import pandas as pd
import numpy as np
import sys
import random

np.set_printoptions(linewidth=200,suppress=True)

#default params
data_types = np.array(["FLOAT","INT","INDEX"])

DEFAULT_MAX = 10000
DEFAULT_MIN = 0

#open config file
filename = "S.config"
config_file = "./data/config/" + filename 
table_name = "./data/tables/" + filename.split('.', 1)[0] + ".txt"
print(table_name)

config = np.genfromtxt(config_file,delimiter=",",skip_header=0,dtype=str)



# generate random with probability p smaller than x
def rand_gen(x,p):
    r = random.uniform(0, 1)
    if(r < p):
        return random.uniform(DEFAULT_MIN,x)
        
    else:
        return random.uniform(x, DEFAULT_MAX)

def populate_column(rng,column):
    for i in range(len(column)):
        column[i] = rand_gen(rng[0],rng[1])
    return column

def populate_column_index(column):
    for i in range(len(column)):
        column[i] = i


def create_table(table_stats):
    rows = int(table_stats[0])
    column_types = np.array([])
    ranges = []
    rng = np.array([])
    for column in table_stats[1:]:
        if np.isin(column,data_types):

            column_types = np.append(column_types,column)
            if(rng.size == 0):
                rng = np.append(rng,[DEFAULT_MAX,1])
            ranges.append(rng)
            rng = np.array([])
        else:
            rng = np.append(rng,float(column))
    ranges.pop(0)
    if(rng.size == 0):
        rng = np.append(rng,[DEFAULT_MAX,1])
    ranges.append(rng)
    
    print(ranges)
    assert(len(column_types) == len(ranges))
    columns = len(column_types)
    table = np.zeros((rows,columns))

    fmt=""
    for i in range(columns):
        
        if(column_types[i] == "INDEX"):
            fmt += " %i "
            populate_column_index(table[:,i])
        elif(column_types[i] == "FLOAT"):
            fmt += " %10.32f"
            populate_column(ranges[i],table[:,i])
        elif(column_types[i] == "INT"):
            fmt += " %i "
            populate_column(ranges[i],table[:,i])
            table[:,i] = table[:,i].astype(int)

    np.savetxt(table_name,table,delimiter=',',fmt=fmt)
    return 


#create_table(config)

def get_col_types(table_stats):
    rows = int(table_stats[0])
    column_types = np.array([])
    ranges = []
    rng = np.array([])
    for column in table_stats[1:]:
        if np.isin(column,data_types):

            column_types = np.append(column_types,column)
            
       
    
    
    
    
    
    
    columns = len(column_types)
    table = np.zeros((rows,columns))

    fmt=""
    for i in range(columns):
        
        if(column_types[i] == "INDEX"):
            fmt += " %i,"
            
        elif(column_types[i] == "FLOAT"):
            fmt += " %10.32f,"
            
        elif(column_types[i] == "INT"):
            fmt += " %i,"
            
    if(fmt[-1]==','):
        fmt = fmt[:-1]

    
    return (column_types,fmt) 








./data/tables/S.txt


In [65]:
c,f = get_col_types(config)
f

' %i, %10.32f'

In [9]:
config
table_stats = config

In [28]:
    rows = int(table_stats[0])
    column_types = np.array([])
    ranges = []
    rng = np.array([])
    for column in table_stats[1:]:
        if np.isin(column,data_types):

            column_types = np.append(column_types,column)
            if(rng.size == 0):
                rng = np.append(rng,[DEFAULT_MAX,1])
            ranges.append(rng)
            rng = np.array([])
        else:
            rng = np.append(rng,float(column))
    ranges.pop(0)
    if(rng.size == 0):
        rng = np.append(rng,[DEFAULT_MAX,1])
    ranges.append(rng)
    
    print(ranges)
    assert(len(column_types) == len(ranges))
    columns = len(column_types)
    table = np.zeros((rows,columns))

    fmt=""
    for i in range(columns):
        
        if(column_types[i] == "INDEX"):
            fmt += " %i,"
            populate_column_index(table[:,i])
        elif(column_types[i] == "FLOAT"):
            fmt += " %10.32f,"
            populate_column(ranges[i],table[:,i])
        elif(column_types[i] == "INT"):
            fmt += " %i,"
            populate_column(ranges[i],table[:,i])
            table[:,i] = table[:,i].astype(int)
    if(fmt[-1] == ','):
        fmt = fmt[:-1]
    np.savetxt(table_name,table,delimiter=',',fmt=fmt)

[array([100. ,   0.1]), array([0.5, 0.2])]


In [13]:
table[:,:]

array([[1674.        , 2075.22503274],
       [ 604.        , 8054.08353482],
       [2878.        , 8073.61016528],
       [ 736.        ,    0.16880007],
       [1225.        , 1031.01491048],
       [1982.        , 3834.15598151],
       [8540.        , 9228.50216768],
       [2437.        , 3948.6128664 ],
       [4055.        , 1859.07408519],
       [5504.        , 6429.44216157]])

In [71]:
fmt[:-1]
len(T)
R

array([[   0.        , 5996.70800824,    1.        ,    4.        ],
       [   1.        , 3870.83997072,    9.        ,    1.        ],
       [   2.        , 1779.30370429,    7.        ,    1.        ],
       [   3.        , 8313.09214048,    8.        ,    2.        ],
       [   4.        ,  590.46062451,    1.        ,    4.        ],
       [   5.        , 7474.45559276,    0.        ,    1.        ],
       [   6.        ,   87.91665264,    6.        ,    1.        ],
       [   7.        , 7537.5259362 ,    7.        ,    4.        ],
       [   8.        , 7532.20416718,    6.        ,    0.        ],
       [   9.        , 8274.34410795,    1.        ,    4.        ]])

In [70]:
table1 = "S"
table2 = "T"
table3 = "R"



table_path = "./data/tables/"

def get_table(tableName,path):
    s = path + tableName + ".txt"

    array = np.genfromtxt(s,delimiter=',')
    
    return array

T = get_table(table2,table_path)
S = get_table(table1,table_path)
R = get_table(table3,table_path)


In [130]:
import numpy as np

results_path = "./groundtruth/"

table_path = "./data/tables/"
config_path = "./data/config/"


def get_col_types(table_stats):
    
    table_stats = np.genfromtxt(table_stats,delimiter=",",skip_header=0,dtype=str)
    rows = int(table_stats[0])
    column_types = np.array([])
    ranges = []
    rng = np.array([])
    for column in table_stats[1:]:
        if np.isin(column,data_types):
            column_types = np.append(column_types,column)
            
    columns = len(column_types)
    table = np.zeros((rows,columns))

    fmt=""
    for i in range(columns):
        
        if(column_types[i] == "INDEX"):
            fmt += " %i,"
            
        elif(column_types[i] == "FLOAT"):
            fmt += " %10.32f,"
            
        elif(column_types[i] == "INT"):
            fmt += " %i,"
            
    if(fmt[-1]==','):
        fmt = fmt[:-1]

    
    return (column_types,fmt) 




def get_table(tableName,path):
    s = path + tableName + ".txt"

    array = np.genfromtxt(s,delimiter=',')
    
    return array

def q1(tablename,col, val):
    # q1
    # Select * from t1 where A > val
    
    
    
    result = []
    T = get_table(tablename,table_path)

    col_types,fmt = get_col_types(config_path + tablename + ".config")
    
    
    
    if(col_types[0]!="INDEX"):
        c = ord(col) - 65 # converting col into int
        
    else: 
        if(col == "ID"):
            c = 0
        else:
            c = ord(col) - 65 # converting col into int
            c += 1 
    
    #### Actual Query

    for i in range(len(T)):

        if(T[i,c] > val):
            result.append(T[i,:])
    
    result = np.vstack(result)

    ### saving
    
    np.savetxt(results_path + "q1_" + tablename + ".csv",result,fmt=fmt)
    

    return

def q2(tablename,col,val):
    

    # q2 
    # Select Sum(D) from t1 where A > val

    result = 0.
    T = get_table(tablename,table_path)

    col_types,fmt = get_col_types(config_path +tablename+".config")
    
    
    
    if(col_types[0]!="INDEX"):
        c = ord(col) - 65 # converting col into int
        
    else: 
        if(col == "ID"):
            c = 0
        else:
            c = ord(col) - 65 # converting col into int
            c += 1 
    
    #### Actual Query

    for i in range(len(T)):
        if(T[i,1] > val):
            result += T[i,4]
    
    ### saving
    
    np.savetxt(results_path + "q2_" + tablename + ".csv",np.array([result]),fmt="%10.32f") # should be only one value

    return
    
def q3(tablename1,col1,tablename2,col2,col3):    
    # q3
    # Select * From R,S Where S.A % R.B = R.C
    
    
    result = []
    R = get_table(tablename2,table_path)
    S = get_table(tablename1,table_path)
    
    col_types1, fmt1 = get_col_types(config_path +tablename1+".config")
    col_types2,fmt2 = get_col_types(config_path +tablename2+".config")
    
    if(col_types1[0]!="INDEX"):
        c1 = ord(col1) - 65 # converting col into int
        
    else: 
        if(col1 == "ID"):
            c1 = 0
        else:
            c1 = ord(col1) - 65 # converting col into int
            c1 += 1 
    
    if(col_types2[0]!="INDEX"):
        c2 = ord(col2) - 65 # converting col into int
        c3 = ord(col3) - 65
         
        
    else: 
        if(col2 == "ID"):
            c2= 0
        else:
            c2 = ord(col2) - 65 # converting col into int
            c3 = ord(col3) - 65
            c2 += 1 
            c3 += 1
    
    
        
    
    for i in range(len(S)):
        for j in range(len(R)):
            if(R[j,c2]!=0):
            
                if(S[i,c1] % R[j,c2] == R[j,c3]):
                    result.append(np.concatenate((R[j,:],S[i,:])))

    result = np.vstack(result)
    
    ### saving
    
    np.savetxt(results_path + "q3_" + tablename1 + "_" + tablename2 + ".csv",result,fmt= fmt1+","+fmt2)
    
    return


In [131]:


val =2400

q1("T",'A',val)

q2("T",'A',val)

q3("S",'A',"R",'B','C')


In [109]:
result

array([[   1.        , 3870.83997072,    9.        ,    1.        , 2863.        , 9826.96086218],
       [   6.        ,   87.91665264,    6.        ,    1.        , 2863.        , 9826.96086218],
       [   3.        , 8313.09214048,    8.        ,    2.        , 9546.        , 6474.85835861],
       [   8.        , 7532.20416718,    6.        ,    0.        , 9546.        , 6474.85835861],
       [   7.        , 7537.5259362 ,    7.        ,    4.        ,  683.        ,    0.22723781],
       [   6.        ,   87.91665264,    6.        ,    1.        , 5305.        ,    0.47199729],
       [   2.        , 1779.30370429,    7.        ,    1.        , 8471.        , 9461.10942444]])